[package]
name = "async-unsync"
version = "0.1.0"
authors = ["Oliver Giersch"]
license = "MIT/Apache-2.0"
repository = "https://github.com/oliver-giersch/async-unsync.git"
categories = ["async", "channel"]
edition = "2021"
exclude = [".github"]

[features]
default = ["std"]
std = []

[dev-dependencies]
futures-lite = "1.12.0"
