name: Rust

on:
  push:
    branches: [ master, develop ]
    tags: [ v*.*.* ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy
      - run: cargo clippy --no-default-features
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --verbose
      - run: cargo test --verbose --no-default-features
      - run: cargo test --verbose --no-default-features --features alloc
      - run: cargo test --verbose --no-default-features --features alloc,std
      - run: cargo test --verbose --no-default-features --features std

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@miri
      - run: cargo miri test
        env:
          MIRIFLAGS: -Zmiri-ignore-leaks